<main class="container py-4" style="max-width: 860px;">
    <div class="mb-4"><h1 class="h3 mb-1"><?= html_escape($page_title); ?></h1><p class="text-muted mb-0">Kolom bertanda <span class="text-danger">*</span> wajib diisi.</p></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-4">
        <?= form_open($mahasiswa ? 'sistem-nilai/master-data/mahasiswa/perbarui/' . $mahasiswa->id : 'sistem-nilai/master-data/mahasiswa/simpan'); ?>
        <div class="row g-3">
            <div class="col-md-4"><label for="nim" class="form-label">NIM <span class="text-danger">*</span></label><input id="nim" name="nim" maxlength="30" required class="form-control <?= form_error('nim') ? 'is-invalid' : ''; ?>" value="<?= html_escape(set_value('nim', $mahasiswa ? $mahasiswa->nim : '')); ?>"><div class="invalid-feedback"><?= form_error('nim'); ?></div></div>
            <div class="col-md-8"><label for="nama" class="form-label">Nama Mahasiswa <span class="text-danger">*</span></label><input id="nama" name="nama" maxlength="150" required class="form-control <?= form_error('nama') ? 'is-invalid' : ''; ?>" value="<?= html_escape(set_value('nama', $mahasiswa ? $mahasiswa->nama : '')); ?>"><div class="invalid-feedback"><?= form_error('nama'); ?></div></div>
            <div class="col-md-4"><label for="jenis_kelamin" class="form-label">Jenis Kelamin</label><?php $jenis_kelamin = set_value('jenis_kelamin', $mahasiswa ? $mahasiswa->jenis_kelamin : ''); ?><select id="jenis_kelamin" name="jenis_kelamin" class="form-select <?= form_error('jenis_kelamin') ? 'is-invalid' : ''; ?>"><option value="">- Pilih -</option><?php foreach ($jenis_kelamin_options as $option): ?><option value="<?= $option; ?>" <?= $jenis_kelamin === $option ? 'selected' : ''; ?>><?= $option === 'L' ? 'Laki-laki' : 'Perempuan'; ?></option><?php endforeach; ?></select><div class="invalid-feedback"><?= form_error('jenis_kelamin'); ?></div></div>
            <div class="col-md-8"><label for="program_studi_id" class="form-label">Program Studi</label><?php $prodi_id = set_value('program_studi_id', $mahasiswa ? $mahasiswa->program_studi_id : ''); ?><select id="program_studi_id" name="program_studi_id" class="form-select <?= form_error('program_studi_id') ? 'is-invalid' : ''; ?>"><option value="">- Pilih Program Studi -</option><?php foreach ($program_studi_options as $prodi): ?><option value="<?= (int) $prodi->id; ?>" <?= (string) $prodi_id === (string) $prodi->id ? 'selected' : ''; ?>><?= html_escape($prodi->kode_prodi . ' — ' . $prodi->nama_prodi . ' (' . $prodi->status . ')'); ?></option><?php endforeach; ?></select><div class="invalid-feedback"><?= form_error('program_studi_id'); ?></div></div>
            <div class="col-md-4"><label for="angkatan" class="form-label">Angkatan</label><input id="angkatan" name="angkatan" type="number" min="1901" max="<?= date('Y') + 1; ?>" placeholder="Contoh: 2026" class="form-control <?= form_error('angkatan') ? 'is-invalid' : ''; ?>" value="<?= html_escape(set_value('angkatan', $mahasiswa ? $mahasiswa->angkatan : '')); ?>"><div class="invalid-feedback"><?= form_error('angkatan'); ?></div></div>
            <div class="col-md-4"><label for="status" class="form-label">Status <span class="text-danger">*</span></label><?php $status = set_value('status', $mahasiswa ? $mahasiswa->status : 'Aktif'); ?><select id="status" name="status" required class="form-select <?= form_error('status') ? 'is-invalid' : ''; ?>"><?php foreach ($status_options as $option): ?><option value="<?= $option; ?>" <?= $status === $option ? 'selected' : ''; ?>><?= $option; ?></option><?php endforeach; ?></select><div class="invalid-feedback"><?= form_error('status'); ?></div></div>
        </div>
        <div class="d-flex gap-2 mt-4"><button type="submit" class="btn btn-success"><i class="bi bi-save"></i> Simpan</button><a href="<?= site_url('sistem-nilai/master-data/mahasiswa'); ?>" class="btn btn-outline-secondary">Batal</a></div>
        <?= form_close(); ?>
    </div></div>
</main>
